export const dashboardText = {
  common: {
    noLink: 'Sin enlace',
    noVisible: 'No visible',
    noCompanyVisible: 'Sin empresa visible',
    notAvailable: 'No disponible',
    noData: 'Sin datos',
    noDataAvailable: 'Todavia no hay datos disponibles.',
    noNews: 'Sin novedades.',
    noFacts: 'Sin hechos disponibles.',
    noPendingApprovals: 'Sin aprobaciones pendientes.',
    noActiveBlocks: 'Sin bloqueos activos.',
    noNewWarnings: 'Sin advertencias nuevas.',
    noteLabel: 'Nota',
    dashboardManualTrigger: 'Ejecucion manual desde el dashboard',
    loadingProfile: 'Cargando perfil maestro...',
    loadingApprovalQueue: 'Cargando bandeja de aprobacion...',
    loadingJobs: 'Cargando vacantes...',
    loadingOperations: 'Cargando estado operativo...',
    loadingApprovals: 'Cargando aprobaciones...',
    loadingAnswers: 'Cargando respuestas...',
    noSubject: 'Sin asunto',
    noSender: 'Sin remitente',
    noSnippet: 'Sin resumen visible',
    yes: 'si',
    no: 'no',
    active: 'activa',
    inactive: 'inactiva',
    apiOfflineTitle: 'No se pudo conectar con JobPilot API.',
    apiOfflineDescription: (apiBaseUrl) =>
      `Verifica que el backend este iniciado y responda en ${apiBaseUrl}.`,
    apiOfflineCheckedAt: (value) => `Ultima verificacion: ${value}`,
    apiOfflineAction: 'Inicia o reinicia el backend y vuelve a intentar.',
    retry: 'Reintentar',
    genericErrorTitle: 'No se pudo completar la operacion.',
    genericErrorAction: 'Revisa los datos y vuelve a intentarlo.',
    validationErrorTitle: 'Hay datos por corregir.',
    validationErrorAction: 'Corrige los campos marcados y vuelve a intentar.',
    automationModeConflictTitle: 'Modo de automatizacion no disponible.',
    automationModeConflictAction:
      'Guarda la configuracion con Manual, Asistido o Simulacion segura.',
    timeoutErrorTitle: 'La solicitud tardo demasiado.',
    timeoutErrorAction: 'Vuelve a intentar en unos segundos.',
  },
  shell: {
    eyebrow: 'JobPilot AI',
    title: 'Pipeline de postulaciones con revision humana',
    subtitle:
      'Carga una vacante manual, analiza compatibilidad con reglas deterministas y revisa que datos necesitan aprobacion antes de preparar un borrador.',
    storageLabel: 'Modo de almacenamiento',
  },
  navigation: {
    eyebrow: 'JobPilot AI',
    title: 'Centro operativo',
    subtitle: 'Navega por las vistas base de la nueva arquitectura sin perder el contexto del agente.',
    menu: 'Menu',
    dashboard: 'Dashboard',
    jobs: 'Vacantes',
    automation: 'Automatizacion',
    automationRuns: 'Ejecuciones',
    integrations: 'Integraciones',
    resumes: 'CVs',
  },
  dashboardOverview: {
    title: 'Resumen ejecutivo del agente',
    subtitle:
      'Concentra metricas, salud operativa, actividad reciente y accesos rapidos sin mezclar la configuracion detallada del runner.',
    quickLinksTitle: 'Accesos rapidos',
    quickLinksSubtitle: 'Usa estas rutas base para comenzar la migracion incremental del frontend.',
    jobsLinkTitle: 'Ir a vacantes',
    jobsLinkDescription:
      'Centraliza intake manual, sesiones supervisadas, previsualizacion del borrador y la bandeja de revision.',
    automationLinkTitle: 'Ir a automatizacion',
    automationLinkDescription:
      'Configura reglas, ventanas operativas y el modo del runner desde una pagina dedicada.',
    automationRunsLinkTitle: 'Ver ejecuciones',
    automationRunsLinkDescription:
      'Revisa simulaciones recientes, ciclos del agente y resultados persistidos sin mezclar configuracion.',
    activityTitle: 'Actividad reciente',
    activitySubtitle: 'Resume vacantes recientes y el estado operativo del agente sin abrir paneles de edicion.',
    recentJobsTitle: 'Vacantes recientes',
    recentJobsEmpty: 'Todavia no hay vacantes recientes para resumir.',
    jobStatusLabel: 'Estado',
    jobScoreLabel: 'Score',
    jobSourceLabel: 'Fuente',
    automationStatusTitle: 'Estado del agente',
    automationStatusSubtitle: 'Referencia rapida del runner y de la ultima actividad registrada.',
    automationEnabledLabel: 'Automatizacion',
    automationModeLabel: 'Modo activo',
    recentRunsLabel: 'Ejecuciones recientes',
    recentApplicationsLabel: 'Postulaciones recientes',
  },
  metrics: {
    total: 'Vacantes analizadas',
    ready: 'Listas para preparar',
    awaitingApproval: 'Pendientes de aprobacion',
    blocked: 'Bloqueadas por reglas',
  },
  form: {
    title: 'Nueva vacante manual',
    subtitle:
      'Pega texto de una publicacion, alerta o correo. El sistema extrae senales visibles y nunca inventa experiencia.',
    rawTextLabel: 'Texto de la vacante',
    rawTextPlaceholder:
      'Ejemplo: Desarrollador Backend - Remoto en Acme Labs...\nEmpresa: Acme Labs\nRequisito: Node.js, Express y MySQL...',
    sourceUrlLabel: 'Enlace original',
    sourceUrlPlaceholder: 'https://www.linkedin.com/jobs/view/...',
    submitIdle: 'Analizar vacante',
    submitBusy: 'Analizando...',
    success: 'Vacante analizada y guardada.',
  },
  profile: {
    title: 'Perfil maestro',
    subtitle:
      'Este perfil se guarda en MySQL y funciona como fuente maestra para matching y futuras postulaciones.',
    saveIdle: 'Guardar perfil',
    saveBusy: 'Guardando...',
    saveSuccess: 'Perfil guardado.',
    name: 'Nombre',
    targetRoles: 'Roles objetivo',
    location: 'Ubicacion',
    english: 'Ingles confirmado',
    availability: 'Disponibilidad',
    salaryAmount: 'Salario base',
    salaryCurrency: 'Moneda',
    salaryPeriod: 'Periodo',
    salaryPeriodLabels: {
      monthly: 'Mensual',
      yearly: 'Anual',
      hourly: 'Por hora',
    },
    github: 'GitHub',
    linkedin: 'LinkedIn',
    email: 'Email principal',
    modalities: 'Modalidades',
    modalityLabels: {
      remote: 'Remoto',
      hybrid: 'Hibrido',
      onsite: 'Presencial',
    },
    projects: 'Proyectos',
    technologies: 'Tecnologias confirmadas',
    knowledgeAreas: 'Conocimientos',
    prohibitedClaims: 'Claims prohibidos',
    listHint: 'Separa multiples valores con comas.',
  },
  resumes: {
    title: 'Gestor de CVs',
    subtitle:
      'Sube versiones locales de tu CV y asigna manualmente la adecuada a cada vacante antes de crear el borrador final.',
    empty: 'Todavia no cargaste ningun CV.',
    uploadLabel: 'Etiqueta del CV',
    uploadPlaceholder: 'Ejemplo: Backend CV EN',
    uploadFile: 'Archivo del CV',
    uploadHelp: 'Formatos permitidos: PDF, DOC y DOCX. Limite maximo: 5 MB.',
    uploadIdle: 'Cargar CV',
    uploadBusy: 'Guardando CV...',
    uploadSuccess: 'CV cargado correctamente.',
    uploadLoading: 'Cargando CVs...',
    fileRequired: 'Selecciona un archivo antes de continuar.',
    invalidFormat: 'Formato no permitido. Usa PDF, DOC o DOCX.',
    invalidMimeType: 'El tipo de archivo no es valido para un CV permitido.',
    fileTooLarge: 'El archivo supera el tamano maximo permitido de 5 MB.',
    availableStatus: 'Disponible para postulaciones',
    selectedStatus: 'Seleccionado para esta vacante',
    uploadedAt: 'Fecha de carga',
    sizeLabel: 'Tamano',
    fileNameLabel: 'Archivo',
    statusLabel: 'Estado',
    assignTitle: 'CV para la vacante actual',
    assignEmptyJob: 'Previsualiza una vacante para elegir el CV a usar en esa postulacion.',
    assignSelectLabel: 'CV seleccionado',
    assignSelectPlaceholder: 'Elige un CV cargado',
    assignIdle: 'Asignar CV',
    assignBusy: 'Asignando CV...',
    clearIdle: 'Quitar CV',
    clearBusy: 'Quitando CV...',
    assignedTo: 'Vacante activa',
    currentSelection: 'Seleccion actual',
    currentSelectionEmpty: 'Sin CV asignado.',
  },
  answers: {
    title: 'Respuestas reutilizables',
    subtitle:
      'Mantiene respuestas frecuentes con certeza y nivel de uso permitido. Lo sensible o desconocido se muestra, pero nunca debe insertarse automaticamente.',
    empty: 'Todavia no hay respuestas reutilizables.',
    kind: 'Tipo',
    question: 'Pregunta',
    answer: 'Respuesta',
    certainty: 'Certeza',
    tags: 'Tags',
    tagsHint: 'Separa tags con comas para facilitar sugerencias por vacante.',
    createIdle: 'Guardar respuesta',
    createBusy: 'Guardando...',
    updateIdle: 'Actualizar',
    updateBusy: 'Actualizando...',
    deleteIdle: 'Eliminar',
    deleteBusy: 'Eliminando...',
    editIdle: 'Editar',
    cancelIdle: 'Cancelar',
    createSuccess: 'Respuesta guardada.',
    usageReferenceOnly: 'Referencia',
    usageReviewRequired: 'Requiere aprobacion',
    usageDoNotUse: 'No usar',
  },
  list: {
    title: 'Vacantes recientes',
    empty: 'Todavia no hay vacantes cargadas.',
    matches: 'Coincidencias',
    gaps: 'Brechas',
    risks: 'Riesgos',
    approvals: 'Requiere aprobacion',
    blocked: 'Bloqueos',
    previewAction: 'Previsualizar borrador',
    previewBusy: 'Generando borrador...',
  },
  approval: {
    title: 'Bandeja de aprobacion',
    empty: 'No hay vacantes pendientes de revision humana.',
    subtitle:
      'Aprueba solo cuando la vacante siga siendo valida y los datos sensibles ya esten verificados por Bryan.',
    approveAction: 'Aprobar',
    approveBusy: 'Aprobando...',
    rejectAction: 'Descartar',
    rejectBusy: 'Descartando...',
    defaultReasonApprove: 'Revision humana completada.',
    defaultReasonReject: 'No continuar con esta vacante.',
  },
  sensitiveApprovals: {
    title: 'Aprobaciones sensibles',
    subtitle:
      'Resuelve salario, ingles, work authorization, relocation, travel y otros datos sensibles antes de crear el borrador real.',
    empty: 'No hay aprobaciones sensibles registradas.',
    filtersTitle: 'Filtros',
    searchLabel: 'Buscar',
    searchPlaceholder: 'Empresa, vacante, motivo o nota',
    statusLabel: 'Estado',
    kindLabel: 'Tipo',
    allStatuses: 'Todos',
    allKinds: 'Todos',
    pendingTitle: 'Pendientes',
    historyTitle: 'Historial reciente',
    reviewerNoteLabel: 'Nota del revisor',
    reviewerNotePlaceholder: 'Ejemplo: salario confirmado por Bryan para esta vacante.',
    approveAction: 'Aprobar dato',
    approveBusy: 'Aprobando dato...',
    rejectAction: 'Rechazar dato',
    rejectBusy: 'Rechazando dato...',
    approveNote: 'Dato sensible revisado y aprobado manualmente.',
    rejectNote: 'Dato sensible no aprobado para esta vacante.',
  },
  audit: {
    title: 'Timeline y auditoria',
    subtitle:
      'Traza los eventos operativos de la vacante activa para entender decisiones, previews, drafts y cambios manuales.',
    empty: 'Todavia no hay eventos de auditoria para este contexto.',
    globalTitle: 'Timeline reciente',
    jobTitle: 'Timeline de la vacante activa',
    entityLabel: 'Entidad',
    eventLabel: 'Evento',
    payloadTitle: 'Detalle',
  },
  operations: {
    title: 'Estado operativo',
    subtitle:
      'Resume salud del backend, cola operativa, integraciones y circuit breakers para detectar degradaciones locales antes de seguir automatizando.',
    apiStatus: 'API',
    overallStatus: 'Estado general',
    storageMode: 'Storage',
    mysqlStatus: 'MySQL',
    queueMode: 'Cola',
    queueStatus: 'Estado cola',
    gmailStatus: 'Gmail',
    openAiStatus: 'OpenAI',
    redisStatus: 'Redis',
    schedulerStatus: 'Scheduler',
    automationStatus: 'Automatizacion',
    automationMode: 'Modo activo',
    killSwitchStatus: 'Kill switch',
    requireHumanApproval: 'Aprobacion humana',
    requestCorrelation: 'Correlacion por request',
    circuitTitle: 'Circuit breakers',
    empty: 'No hay datos operativos disponibles.',
  },
  draft: {
    title: 'Previsualizacion del borrador',
    empty: 'Genera un borrador desde una vacante para revisar asunto, cuerpo y advertencias antes de Gmail.',
    recipient: 'Destinatario',
    subject: 'Asunto',
    selectedResume: 'CV seleccionado',
    selectedResumeEmpty: 'Sin CV asignado',
    suggestedAnswers: 'Respuestas sugeridas',
    suggestedAnswersEmpty: 'No hay respuestas reutilizables relevantes para esta vacante.',
    sensitiveApprovals: 'Aprobaciones sensibles',
    sensitiveApprovalsEmpty: 'No hay aprobaciones sensibles vinculadas a esta vacante.',
    body: 'Cuerpo',
    highlights: 'Puntos fuertes usados',
    facts: 'Hechos utilizados',
    warnings: 'Advertencias',
    blocked: 'Bloqueado',
    approvals: 'Aprobaciones requeridas',
    statusReady: 'Listo para revisar',
    statusReview: 'Requiere revision humana',
    statusBlocked: 'No debe prepararse',
    gmailDraftIdle: 'Crear borrador en Gmail',
    gmailDraftBusy: 'Creando borrador en Gmail...',
    gmailDraftSuccess: 'Borrador creado en Gmail.',
    gmailDraftConnectHint: 'Conecta Gmail para crear el borrador real.',
    gmailDraftAttachmentAttached: 'El CV se adjunto automaticamente al borrador.',
    gmailDraftAttachmentManual: 'El CV todavia requiere adjunto manual.',
    dryRunIdle: 'Probar automatizacion sin enviar',
    dryRunBusy: 'Ejecutando simulacion segura...',
    dryRunSuccess: 'Simulacion segura registrada.',
  },
  automation: {
    title: 'Runner de automatizacion',
    subtitle:
      'Configura el ciclo diario del agente con datos reales. La simulacion segura prepara, analiza y registra evidencias, pero nunca envia postulaciones reales.',
    enabled: 'Automatizacion habilitada',
    mode: 'Modo',
    timezone: 'Zona horaria',
    startTime: 'Hora de inicio',
    dailyApplicationLimit: 'Limite diario de postulaciones',
    dailyDiscoveryLimit: 'Limite diario de descubrimiento',
    minimumMatchScore: 'Score minimo',
    requireHumanApproval: 'Mantener aprobacion humana',
    allowedSources: 'Fuentes habilitadas',
    allowedRoles: 'Roles habilitados',
    blockedCompanies: 'Empresas bloqueadas',
    blockedKeywords: 'Palabras bloqueadas',
    sourcePolicies: 'Politicas por fuente',
    saveIdle: 'Guardar automatizacion',
    saveBusy: 'Guardando automatizacion...',
    triggerIdle: 'Probar automatizacion sin enviar',
    triggerBusy: 'Ejecutando ciclo...',
    success: 'Configuracion guardada.',
    triggerSuccess: 'Simulacion segura ejecutada.',
    triggerDescription:
      'Usa tus vacantes, perfil y reglas reales para comprobar que haria el agente sin enviar ninguna postulacion.',
    listHint: 'Separa varios valores con comas.',
    modeHelp:
      'En esta fase no se puede guardar Automatico. Solo estan disponibles Manual, Asistido y Simulacion segura.',
    activeDays: 'Dias activos',
    allowedSeniorities: 'Seniorities habilitados',
    allowedWorkModes: 'Modalidades habilitadas',
    modes: {
      MANUAL: 'MANUAL',
      ASSISTED: 'ASSISTED',
      DRY_RUN: 'DRY_RUN',
    },
    days: {
      0: 'Domingo',
      1: 'Lunes',
      2: 'Martes',
      3: 'Miercoles',
      4: 'Jueves',
      5: 'Viernes',
      6: 'Sabado',
    },
    seniorities: {
      junior: 'Junior',
      unknown: 'Sin definir',
      semi_senior: 'Semi senior',
      senior: 'Senior',
    },
    workModes: {
      remote: 'Remoto',
      hybrid: 'Hibrido',
      onsite: 'Presencial',
    },
    sourceLabels: {
      MANUAL: 'Manual',
      LINKEDIN_JOBS_SUPERVISED: 'LinkedIn Jobs supervisado',
      LINKEDIN_FEED_SUPERVISED: 'LinkedIn Feed supervisado',
      LINKEDIN_POST_SEARCH_SUPERVISED: 'LinkedIn Post Search supervisado',
    },
  },
  automationPage: {
    title: 'Centro de automatizacion',
    subtitle:
      'Administra la configuracion del runner y dispara simulaciones seguras sin cargar el dashboard ejecutivo.',
    workspaceTitle: 'Siguientes vistas operativas',
    workspaceSubtitle:
      'La configuracion vive aqui. Las ejecuciones y la operacion diaria ya se separan en rutas dedicadas.',
    jobsLinkTitle: 'Abrir vacantes',
    jobsLinkDescription: 'Gestiona intake, revision humana, capturas supervisadas y borradores desde /jobs.',
    runsLinkTitle: 'Abrir ejecuciones',
    runsLinkDescription: 'Consulta postulaciones simuladas y ciclos del runner desde /automation/runs.',
  },
  automationRunsPage: {
    title: 'Ejecuciones del runner',
    subtitle:
      'Consulta simulaciones, resultados y ciclos recientes del agente sin tocar la configuracion del runner.',
    workspaceTitle: 'Atajos operativos',
    workspaceSubtitle:
      'Usa estas rutas para volver a la configuracion o abrir la gestion de vacantes segun el siguiente paso.',
    automationLinkTitle: 'Volver a automatizacion',
    automationLinkDescription: 'Ajusta limites, horarios, filtros y modo del runner.',
    jobsLinkTitle: 'Abrir vacantes',
    jobsLinkDescription: 'Revisa intake, aprobaciones y previsualizaciones del borrador.',
  },
  jobsPage: {
    title: 'Operacion de vacantes',
    subtitle:
      'Centraliza intake manual, capturas supervisadas, previsualizacion del borrador y revision humana sin mezclar configuracion del runner.',
  },
  applications: {
    title: 'Postulaciones y ejecuciones',
    subtitle:
      'Muestra las simulaciones manuales y los ciclos de automatizacion recientes con datos reales, estado final y evidencia resumida.',
    emptyApplications: 'Todavia no hay postulaciones registradas.',
    emptyRuns: 'Todavia no se ejecuto ninguna automatizacion.',
    applicationsTitle: 'Simulaciones recientes',
    runsTitle: 'Ejecuciones recientes',
    resultLabel: 'Resultado',
    timelineLabel: 'Pasos',
    sourceLabel: 'Fuente',
    summaryLabel: 'Resumen',
    startedAtLabel: 'Fecha y hora',
    modeLabel: 'Modo',
    durationLabel: 'Duracion',
    processedLabel: 'Vacantes procesadas',
    completedLabel: 'Completadas',
    awaitingApprovalLabel: 'Pendientes de aprobacion',
    blockedLabel: 'Bloqueadas',
    duplicatesLabel: 'Duplicadas',
    failedLabel: 'Con error',
    stopReasonLabel: 'Motivo',
  },
  gmail: {
    title: 'Integracion Gmail',
    workspaceEyebrow: 'Google Workspace',
    statusLoading: 'Cargando estado de Gmail...',
    notConfigured: 'No configurada',
    notConfiguredDescription: 'La integracion Gmail todavia no esta configurada en el backend.',
    notConfiguredHelp:
      'Completa las variables OAuth de Google en el backend para habilitar la conexion desde esta pantalla.',
    disconnected: 'Gmail no conectado',
    connected: 'Gmail conectado',
    connect: 'Conectar Gmail',
    connecting: 'Abriendo autorizacion...',
    disconnect: 'Desconectar',
    emailLabel: 'Email',
    labelLabel: 'Etiqueta',
    alertsTitle: 'Alertas recientes',
    alertsEmpty: 'No hay alertas para la consulta actual.',
    alertsLoading: 'Cargando alertas...',
    alertsConnectHint: 'Conecta Gmail para revisar alertas y crear borradores reales.',
    createLabelNote:
      'Gmail no permite aplicar etiquetas personalizadas a drafts. La etiqueta se mantiene para flujos de alertas y tracking interno.',
    attachmentNote: 'Antes de enviar, adjunta manualmente el CV correcto.',
  },
  browserSessions: {
    title: 'Sesiones supervisadas de LinkedIn',
    subtitle:
      'Abre una sesion visible y local de LinkedIn Jobs, Feed o busqueda de publicaciones, navega manualmente y captura solo la vacante o publicacion que estes viendo. Nunca aplica ni envia nada automaticamente.',
    providerLabel: 'Contexto supervisado',
    providerHint:
      'Usa Jobs para ofertas clasicas, Feed para publicaciones del inicio y Post Search para resultados del buscador de publicaciones.',
    providers: {
      LINKEDIN_JOBS: 'LinkedIn Jobs',
      LINKEDIN_FEED: 'LinkedIn Feed',
      LINKEDIN_POST_SEARCH: 'LinkedIn Post Search',
    },
    startIdle: 'Iniciar sesion visible',
    startBusy: 'Abriendo sesion...',
    navigateLabel: 'URL de LinkedIn',
    navigatePlaceholder: 'https://www.linkedin.com/...',
    navigateIdle: 'Ir a URL',
    navigateBusy: 'Navegando...',
    refreshIdle: 'Refrescar estado',
    refreshBusy: 'Refrescando...',
    captureIdle: 'Capturar contenido visible',
    captureBusy: 'Capturando...',
    closeIdle: 'Cerrar sesion',
    closeBusy: 'Cerrando...',
    empty: 'Todavia no hay sesiones supervisadas abiertas.',
    attentionTitle: 'Requiere atencion humana',
    loginRequiredTitle: 'LinkedIn requiere iniciar sesion.',
    loginRequiredDescription:
      'Inicia sesion manualmente en la ventana supervisada, completa MFA o CAPTCHA si aparece y luego verifica el estado.',
    verifyLoginIdle: 'Ya inicie sesion - verificar',
    verifyLoginBusy: 'Verificando sesion...',
    reusedStoredSession: 'Sesion autenticada reutilizada',
    reusedStoredSessionDescription:
      'Se cargo una sesion guardada previamente para este contexto supervisado.',
    runtimeLabel: 'Runtime',
    runtimeLocal: 'Ventana local visible',
    runtimeBrowserless: 'Browserless remoto',
    remoteRuntimeNotice:
      'Esta sesion corre en Browserless. El login manual requiere abrir el visor remoto del navegador.',
    remoteRuntimePending:
      'El backend ya puede usar Browserless, pero el acceso al visor remoto desde la app requiere una URL de depuracion protegida.',
    lastCaptured: 'Ultima vacante capturada',
    surfaceLabel: 'Superficie detectada',
    surfaces: {
      jobs: 'Jobs',
      feed: 'Feed',
      search: 'Busqueda de publicaciones',
      post: 'Publicacion individual',
      unknown: 'Sin clasificar',
    },
    hiringSignals: 'Senales de contratacion visibles',
    hiringSignalsEmpty: 'Sin senales de contratacion visibles.',
    visibleEmails: 'Correos visibles',
    visibleEmailsEmpty: 'Sin correos visibles.',
    runtimeUnavailable: 'La sesion ya no esta activa en este proceso. Inicia una nueva si la cerraste o reiniciaste el backend.',
  },
};
