export const dashboardText = {
  shell: {
    eyebrow: 'JobPilot AI',
    title: 'Pipeline de postulaciones con revision humana',
    subtitle:
      'Carga una vacante manual, analiza compatibilidad con reglas deterministas y revisa que datos necesitan aprobacion antes de preparar un borrador.',
    storageLabel: 'Modo de almacenamiento',
  },
  metrics: {
    total: 'Vacantes analizadas',
    ready: 'Listas para preparar',
    awaitingApproval: 'Pendientes de aprobacion',
    blocked: 'Bloqueadas por reglas',
  },
  form: {
    title: 'Nueva vacante manual',
    subtitle:
      'Pega texto de una publicacion, alerta o correo. El sistema extrae senales visibles y nunca inventa experiencia.',
    rawTextLabel: 'Texto de la vacante',
    rawTextPlaceholder:
      'Ejemplo: Backend Developer - Remote at Acme Labs...\nEmpresa: Acme Labs\nRequisito: Node.js, Express y MySQL...',
    sourceUrlLabel: 'Enlace original',
    sourceUrlPlaceholder: 'https://www.linkedin.com/jobs/view/...',
    submitIdle: 'Analizar vacante',
    submitBusy: 'Analizando...',
    success: 'Vacante analizada y guardada.',
  },
  profile: {
    title: 'Perfil maestro',
    subtitle:
      'Este perfil se guarda en MySQL y funciona como fuente maestra para matching y futuras postulaciones.',
    saveIdle: 'Guardar perfil',
    saveBusy: 'Guardando...',
    saveSuccess: 'Perfil guardado.',
    name: 'Nombre',
    targetRoles: 'Roles objetivo',
    location: 'Ubicacion',
    english: 'Ingles confirmado',
    availability: 'Disponibilidad',
    salaryAmount: 'Salario base',
    salaryCurrency: 'Moneda',
    salaryPeriod: 'Periodo',
    github: 'GitHub',
    linkedin: 'LinkedIn',
    email: 'Email principal',
    modalities: 'Modalidades',
    projects: 'Proyectos',
    technologies: 'Tecnologias confirmadas',
    knowledgeAreas: 'Conocimientos',
    prohibitedClaims: 'Claims prohibidos',
    listHint: 'Separa multiples valores con comas.',
  },
  resumes: {
    title: 'Gestor de CVs',
    subtitle:
      'Sube versiones locales de tu CV y asigna manualmente la adecuada a cada vacante antes de crear el borrador final.',
    empty: 'Todavia no hay CVs cargados.',
    uploadLabel: 'Etiqueta del CV',
    uploadPlaceholder: 'Ejemplo: Backend CV EN',
    uploadFile: 'Archivo del CV',
    uploadHelp: 'Formatos permitidos: PDF, DOC y DOCX. Limite recomendado: 5 MB.',
    uploadIdle: 'Guardar CV',
    uploadBusy: 'Guardando CV...',
    uploadSuccess: 'CV guardado.',
    assignTitle: 'CV para la vacante actual',
    assignEmptyJob: 'Previsualiza una vacante para elegir el CV a usar en esa postulacion.',
    assignSelectLabel: 'CV seleccionado',
    assignSelectPlaceholder: 'Elige un CV cargado',
    assignIdle: 'Asignar CV',
    assignBusy: 'Asignando CV...',
    clearIdle: 'Quitar CV',
    clearBusy: 'Quitando CV...',
    assignedTo: 'Vacante activa',
    currentSelection: 'Seleccion actual',
    currentSelectionEmpty: 'Sin CV asignado.',
  },
  answers: {
    title: 'Respuestas reutilizables',
    subtitle:
      'Mantiene respuestas frecuentes con certeza y nivel de uso permitido. Lo sensible o desconocido se muestra, pero nunca debe insertarse automaticamente.',
    empty: 'Todavia no hay respuestas reutilizables.',
    kind: 'Tipo',
    question: 'Pregunta',
    answer: 'Respuesta',
    certainty: 'Certeza',
    tags: 'Tags',
    tagsHint: 'Separa tags con comas para facilitar sugerencias por vacante.',
    createIdle: 'Guardar respuesta',
    createBusy: 'Guardando...',
    updateIdle: 'Actualizar',
    updateBusy: 'Actualizando...',
    deleteIdle: 'Eliminar',
    deleteBusy: 'Eliminando...',
    editIdle: 'Editar',
    cancelIdle: 'Cancelar',
    createSuccess: 'Respuesta guardada.',
    usageReferenceOnly: 'Referencia',
    usageReviewRequired: 'Requiere aprobacion',
    usageDoNotUse: 'No usar',
  },
  list: {
    title: 'Vacantes recientes',
    empty: 'Todavia no hay vacantes cargadas.',
    matches: 'Coincidencias',
    gaps: 'Brechas',
    risks: 'Riesgos',
    approvals: 'Requiere aprobacion',
    blocked: 'Bloqueos',
    previewAction: 'Previsualizar borrador',
    previewBusy: 'Generando borrador...',
  },
  approval: {
    title: 'Bandeja de aprobacion',
    empty: 'No hay vacantes pendientes de revision humana.',
    subtitle:
      'Aprueba solo cuando la vacante siga siendo valida y los datos sensibles ya esten verificados por Bryan.',
    approveAction: 'Aprobar',
    approveBusy: 'Aprobando...',
    rejectAction: 'Descartar',
    rejectBusy: 'Descartando...',
    defaultReasonApprove: 'Revision humana completada.',
    defaultReasonReject: 'No continuar con esta vacante.',
  },
  sensitiveApprovals: {
    title: 'Aprobaciones sensibles',
    subtitle:
      'Resuelve salario, ingles, work authorization, relocation, travel y otros datos sensibles antes de crear el borrador real.',
    empty: 'No hay aprobaciones sensibles registradas.',
    filtersTitle: 'Filtros',
    searchLabel: 'Buscar',
    searchPlaceholder: 'Empresa, vacante, motivo o nota',
    statusLabel: 'Estado',
    kindLabel: 'Tipo',
    allStatuses: 'Todos',
    allKinds: 'Todos',
    pendingTitle: 'Pendientes',
    historyTitle: 'Historial reciente',
    reviewerNoteLabel: 'Nota del revisor',
    reviewerNotePlaceholder: 'Ejemplo: salario confirmado por Bryan para esta vacante.',
    approveAction: 'Aprobar dato',
    approveBusy: 'Aprobando dato...',
    rejectAction: 'Rechazar dato',
    rejectBusy: 'Rechazando dato...',
    approveNote: 'Dato sensible revisado y aprobado manualmente.',
    rejectNote: 'Dato sensible no aprobado para esta vacante.',
  },
  audit: {
    title: 'Timeline y auditoria',
    subtitle:
      'Traza los eventos operativos de la vacante activa para entender decisiones, previews, drafts y cambios manuales.',
    empty: 'Todavia no hay eventos de auditoria para este contexto.',
    globalTitle: 'Timeline reciente',
    jobTitle: 'Timeline de la vacante activa',
    entityLabel: 'Entidad',
    eventLabel: 'Evento',
    payloadTitle: 'Detalle',
  },
  operations: {
    title: 'Estado operativo',
    subtitle:
      'Resume salud del backend, cola operativa, integraciones y circuit breakers para detectar degradaciones locales antes de seguir automatizando.',
    overallStatus: 'Estado general',
    storageMode: 'Storage',
    queueMode: 'Cola',
    queueStatus: 'Estado cola',
    gmailStatus: 'Gmail',
    openAiStatus: 'OpenAI',
    redisConfigured: 'Redis configurado',
    requestCorrelation: 'Correlacion por request',
    circuitTitle: 'Circuit breakers',
    empty: 'No hay datos operativos disponibles.',
  },
  draft: {
    title: 'Previsualizacion del borrador',
    empty: 'Genera un borrador desde una vacante para revisar asunto, cuerpo y advertencias antes de Gmail.',
    recipient: 'Destinatario',
    subject: 'Asunto',
    selectedResume: 'CV seleccionado',
    selectedResumeEmpty: 'Sin CV asignado',
    suggestedAnswers: 'Respuestas sugeridas',
    suggestedAnswersEmpty: 'No hay respuestas reutilizables relevantes para esta vacante.',
    sensitiveApprovals: 'Aprobaciones sensibles',
    sensitiveApprovalsEmpty: 'No hay aprobaciones sensibles vinculadas a esta vacante.',
    body: 'Cuerpo',
    highlights: 'Puntos fuertes usados',
    facts: 'Hechos utilizados',
    warnings: 'Advertencias',
    blocked: 'Bloqueado',
    approvals: 'Aprobaciones requeridas',
    statusReady: 'Listo para revisar',
    statusReview: 'Requiere revision humana',
    statusBlocked: 'No debe prepararse',
    gmailDraftIdle: 'Crear borrador en Gmail',
    gmailDraftBusy: 'Creando borrador en Gmail...',
    gmailDraftSuccess: 'Borrador creado en Gmail.',
    gmailDraftConnectHint: 'Conecta Gmail para crear el borrador real.',
    gmailDraftAttachmentAttached: 'CV adjunto automaticamente al draft.',
    gmailDraftAttachmentManual: 'El CV todavia requiere adjunto manual.',
  },
  gmail: {
    title: 'Integracion Gmail',
    disconnected: 'Gmail no conectado',
    connected: 'Gmail conectado',
    connect: 'Conectar Gmail',
    connecting: 'Abriendo autorizacion...',
    disconnect: 'Desconectar',
    alertsTitle: 'Alertas recientes',
    alertsEmpty: 'No hay alertas para la consulta actual.',
    alertsLoading: 'Cargando alertas...',
    createLabelNote:
      'Gmail no permite aplicar etiquetas personalizadas a drafts. La etiqueta se mantiene para flujos de alertas y tracking interno.',
    attachmentNote: 'Antes de enviar, adjunta manualmente el CV correcto.',
  },
  browserSessions: {
    title: 'Sesiones supervisadas de LinkedIn',
    subtitle:
      'Abre una sesion visible y local de LinkedIn Jobs, Feed o busqueda de publicaciones, navega manualmente y captura solo la vacante o publicacion que estes viendo. Nunca aplica ni envia nada automaticamente.',
    providerLabel: 'Contexto supervisado',
    providerHint:
      'Usa Jobs para ofertas clasicas, Feed para publicaciones del inicio y Post Search para resultados del buscador de publicaciones.',
    providers: {
      LINKEDIN_JOBS: 'LinkedIn Jobs',
      LINKEDIN_FEED: 'LinkedIn Feed',
      LINKEDIN_POST_SEARCH: 'LinkedIn Post Search',
    },
    startIdle: 'Iniciar sesion visible',
    startBusy: 'Abriendo sesion...',
    navigateLabel: 'URL de LinkedIn',
    navigatePlaceholder: 'https://www.linkedin.com/...',
    navigateIdle: 'Ir a URL',
    navigateBusy: 'Navegando...',
    refreshIdle: 'Refrescar estado',
    refreshBusy: 'Refrescando...',
    captureIdle: 'Capturar contenido visible',
    captureBusy: 'Capturando...',
    closeIdle: 'Cerrar sesion',
    closeBusy: 'Cerrando...',
    empty: 'Todavia no hay sesiones supervisadas abiertas.',
    attentionTitle: 'Requiere atencion humana',
    lastCaptured: 'Ultima vacante capturada',
    surfaceLabel: 'Superficie detectada',
    surfaces: {
      jobs: 'Jobs',
      feed: 'Feed',
      search: 'Busqueda de publicaciones',
      post: 'Publicacion individual',
      unknown: 'Sin clasificar',
    },
    hiringSignals: 'Senales de contratacion visibles',
    hiringSignalsEmpty: 'Sin senales de contratacion visibles.',
    visibleEmails: 'Correos visibles',
    visibleEmailsEmpty: 'Sin correos visibles.',
    runtimeUnavailable: 'La sesion ya no esta activa en este proceso. Inicia una nueva si la cerraste o reiniciaste el backend.',
  },
};
